/* Polinomios.java */
/* Generated By:JavaCC: Do not edit this line. Polinomios.java */
public class Polinomios implements PolinomiosConstants {

    public static void main(String[] args) {

        try {

            Polinomios parser = new Polinomios(System.in);
            parser.programa();


                System.out.println("      ANALISIS       ");

                System.out.println("\nEl programa cumple con las reglas del lenguaje.");

                System.out.println("\nValidaciones realizadas:");
                System.out.println("\u2192 Analisis lexico      [ OK ]");
                System.out.println("\u2192 Analisis sintactico  [ OK ]");
                System.out.println("\u2192 Verificacion general [ OK ]");

                System.out.println("\nNo se encontraron errores.\n");

        }

        // ERROR SINTACTICO 
        catch (ParseException e) {

            Token t = e.currentToken.next;

            System.out.println("        ERROR SINTACTICO");

            System.out.println("\nSe encontro un problema en la estructura del programa.\n");

            System.out.println("\u2192 Linea     : " + t.beginLine);
            System.out.println("\u2192 Columna   : " + t.beginColumn);
            System.out.println("\u2192 Simbolo   : " + t.image);

            System.out.println("\nDescripcion:");

            if (t.image.equals("}")) {

                System.out.println("Falta ';' antes de cerrar el bloque.");

            }

            else if (t.image.equals(")")) {

                System.out.println("Falta una expresion o hay parentesis desbalanceados.");

            }

            else if (t.image.equals("else")) {

                System.out.println("El bloque else esta mal ubicado.");

            }

            else if (t.image.equals(";")) {

                System.out.println("Hay una instruccion incompleta.");

            }

            else {

                System.out.println("La estructura ingresada no coincide con la gramatica.");

            }

            System.out.println("\nSugerencia:");
            System.out.println("Revisa la instruccion cercana al simbolo indicado.\n");
        }

        //  ERROR LEXICO 
        catch (TokenMgrError e) {

            String mensaje = e.getMessage();

            int linea = 0;
            int columna = 0;
            String simbolo = "?";

            try {

                // ===== LINEA =====
                int inicioLinea = mensaje.indexOf("line ");
                int finLinea = mensaje.indexOf(",", inicioLinea);

                String textoLinea =
                    mensaje.substring(inicioLinea + 5, finLinea);

                linea = Integer.parseInt(textoLinea.trim());


                //  COLUMNA 
                int inicioColumna = mensaje.indexOf("column ");
                int finColumna = mensaje.indexOf(".", inicioColumna);

                String textoColumna =
                    mensaje.substring(inicioColumna + 7, finColumna);

                columna = Integer.parseInt(textoColumna.trim());


                //  CARACTER 
                int primeraComilla = mensaje.indexOf("'");

                int segundaComilla =
                    mensaje.indexOf("'", primeraComilla + 1);

                simbolo =
                    mensaje.substring(
                        primeraComilla + 1,
                        segundaComilla
                    );

            }

            catch(Exception ex) {

                System.out.println("\nNo se pudo interpretar el error lexico.\n");
            }


            System.out.println("          ERROR LEXICO");

            System.out.println("\nSe detecto un simbolo invalido.\n");

            System.out.println("\u2192 Linea     : " + linea);
            System.out.println("\u2192 Columna   : " + columna);
            System.out.println("\u2192 Caracter  : " + simbolo);

            System.out.println("\nDescripcion:");
            System.out.println("El simbolo no pertenece al lenguaje.");

            System.out.println("\nSugerencia:");
            System.out.println("Utiliza un simbolo valido dentro de la gramatica.\n");
        }
    }

// PARSER


//  PROGRAMA
  static final public 
void programa() throws ParseException {
    jj_consume_token(PROGRAMA);
    jj_consume_token(LLAVE_A);
    inicio();
    instrucciones();
    jj_consume_token(LLAVE_C);
    jj_consume_token(0);
}

//  INICIO 
  static final public 
void inicio() throws ParseException {
    jj_consume_token(INICIO);
    jj_consume_token(LLAVE_A);
    declaraciones();
    jj_consume_token(LLAVE_C);
}

//  BLOQUE 
  static final public 
void bloque() throws ParseException {
    jj_consume_token(LLAVE_A);
    instrucciones();
    jj_consume_token(LLAVE_C);
}

//  DECLARACIONES 
  static final public 
void declaraciones() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(TIPO);
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASIG:{
        jj_consume_token(ASIG);
        expresion();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      jj_consume_token(PYC);
    }
}

// INSTRUCCIONES 
  static final public 
void instrucciones() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case REDUCIR:
      case EVALUAR:
      case EXPANDIR:
      case FACTORIZAR:
      case ORDENAR:
      case LEER:
      case IMPRIMIR:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      instruccion();
    }
}

//  INSTRUCCION 
  static final public 
void instruccion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      asignacion();
      break;
      }
    case REDUCIR:
    case EVALUAR:
    case EXPANDIR:
    case FACTORIZAR:
    case ORDENAR:
    case LEER:
    case IMPRIMIR:{
      funcion();
      break;
      }
    case IF:{
      condicional();
      break;
      }
    case WHILE:{
      ciclo();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// ===== ASIGNACION =====
  static final public 
void asignacion() throws ParseException {
    jj_consume_token(ID);
    jj_consume_token(ASIG);
    expresion();
    jj_consume_token(PYC);
}

// EXPRESIONES 
  static final public 
void expresion() throws ParseException {
    exp_or();
}

// OR 
  static final public 
void exp_or() throws ParseException {
    exp_and();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(OR);
      exp_and();
    }
}

//  AND 
  static final public 
void exp_and() throws ParseException {
    exp_rel();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      jj_consume_token(AND);
      exp_rel();
    }
}

//  RELACIONALES 
  static final public 
void exp_rel() throws ParseException {
    exp_arit();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAYORIG:
    case MENORIG:
    case IGUAL:
    case DIF:
    case MAYOR:
    case MENOR:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAYOR:{
        jj_consume_token(MAYOR);
        break;
        }
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAYORIG:{
        jj_consume_token(MAYORIG);
        break;
        }
      case MENORIG:{
        jj_consume_token(MENORIG);
        break;
        }
      case IGUAL:{
        jj_consume_token(IGUAL);
        break;
        }
      case DIF:{
        jj_consume_token(DIF);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      exp_arit();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
}

//  ARITMETICAS 
  static final public 
void exp_arit() throws ParseException {
    termino();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:
      case MENOS:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        jj_consume_token(MAS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      termino();
    }
}

//  TERMINOS 
  static final public 
void termino() throws ParseException {
    factorMultiplicativo();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MUL:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MUL:{
        jj_consume_token(MUL);
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      factorMultiplicativo();
    }
}

//  MULTIPLICACION IMPLICITA
  static final public 
void factorMultiplicativo() throws ParseException {
    potencia();
    label_7:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_7;
      }
      potencia();
    }
}

//  POTENCIAS 
  static final public 
void potencia() throws ParseException {
    unario();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POT:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_8;
      }
      jj_consume_token(POT);
      unario();
    }
}

//  UNARIO 
  static final public 
void unario() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MENOS:{
      jj_consume_token(MENOS);
      unario();
      break;
      }
    case TRUE:
    case FALSE:
    case ID:
    case NUM:
    case PAR_A:{
      primario();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//  PRIMARIO 
  static final public 
void primario() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PAR_A:{
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      break;
      }
    case ID:
    case NUM:{
      polinomio();
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//  POLINOMIOS 
  static final public 
void polinomio() throws ParseException {
    if (jj_2_2(3)) {
      jj_consume_token(NUM);
      jj_consume_token(ID);
      jj_consume_token(POT);
      jj_consume_token(NUM);
    } else if (jj_2_3(2)) {
      jj_consume_token(NUM);
      jj_consume_token(ID);
    } else if (jj_2_4(3)) {
      jj_consume_token(ID);
      jj_consume_token(POT);
      jj_consume_token(NUM);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case NUM:{
        jj_consume_token(NUM);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

//  FUNCIONES 
  static final public 

void funcion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEER:{
      jj_consume_token(LEER);
      jj_consume_token(ID);
      jj_consume_token(PYC);
      break;
      }
    case IMPRIMIR:{
      jj_consume_token(IMPRIMIR);
      expresion();
      jj_consume_token(PYC);
      break;
      }
    case REDUCIR:{
      jj_consume_token(REDUCIR);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      jj_consume_token(PYC);
      break;
      }
    case EVALUAR:{
      jj_consume_token(EVALUAR);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      jj_consume_token(PYC);
      break;
      }
    case EXPANDIR:{
      jj_consume_token(EXPANDIR);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      jj_consume_token(PYC);
      break;
      }
    case FACTORIZAR:{
      jj_consume_token(FACTORIZAR);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      jj_consume_token(PYC);
      break;
      }
    case ORDENAR:{
      jj_consume_token(ORDENAR);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      jj_consume_token(PYC);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//  CONTROL 
  static final public 
void condicional() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(PAR_A);
    expresion();
    jj_consume_token(PAR_C);
    bloque();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELIF:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_9;
      }
      jj_consume_token(ELIF);
      jj_consume_token(PAR_A);
      expresion();
      jj_consume_token(PAR_C);
      bloque();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      bloque();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
}

//  WHILE 
  static final public 
void ciclo() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(PAR_A);
    expresion();
    jj_consume_token(PAR_C);
    bloque();
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_3R_exp_or_322_5_20()
 {
    if (jj_3R_exp_and_335_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_exp_arit_368_5_23()
 {
    if (jj_3R_termino_384_5_24()) return true;
    return false;
  }

  static private boolean jj_3R_potencia_413_5_10()
 {
    if (jj_3R_unario_426_7_11()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_potencia_415_9_12()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(POT)) return true;
    if (jj_scan_token(NUM)) return true;
    return false;
  }

  static private boolean jj_3R_expresion_313_5_18()
 {
    if (jj_3R_exp_or_322_5_20()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_potencia_413_5_10()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(NUM)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(NUM)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(POT)) return true;
    return false;
  }

  static private boolean jj_3R_polinomio_448_7_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_factorMultiplicativo_400_5_25()
 {
    if (jj_3R_potencia_413_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_exp_rel_348_5_22()
 {
    if (jj_3R_exp_arit_368_5_23()) return true;
    return false;
  }

  static private boolean jj_3R_primario_437_7_17()
 {
    if (jj_3R_polinomio_448_7_19()) return true;
    return false;
  }

  static private boolean jj_3R_primario_436_7_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_primario_436_7_16()) {
    jj_scanpos = xsp;
    if (jj_3R_primario_437_7_17()) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_primario_436_7_16()
 {
    if (jj_scan_token(PAR_A)) return true;
    if (jj_3R_expresion_313_5_18()) return true;
    return false;
  }

  static private boolean jj_3R_termino_384_5_24()
 {
    if (jj_3R_factorMultiplicativo_400_5_25()) return true;
    return false;
  }

  static private boolean jj_3R_exp_and_335_5_21()
 {
    if (jj_3R_exp_rel_348_5_22()) return true;
    return false;
  }

  static private boolean jj_3R_unario_427_7_14()
 {
    if (jj_3R_primario_436_7_15()) return true;
    return false;
  }

  static private boolean jj_3R_unario_426_7_13()
 {
    if (jj_scan_token(MENOS)) return true;
    if (jj_3R_unario_426_7_11()) return true;
    return false;
  }

  static private boolean jj_3R_unario_426_7_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_unario_426_7_13()) {
    jj_scanpos = xsp;
    if (jj_3R_unario_427_7_14()) return true;
    }
    return false;
  }

  static private boolean jj_3R_potencia_415_9_12()
 {
    if (jj_scan_token(POT)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public PolinomiosTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x100000,0x0,0x23fc80,0x23fc80,0x20000000,0x10000000,0x80000000,0x80000000,0x1800000,0x1800000,0x6000000,0x6000000,0x8000000,0x16c0000,0x6c0000,0x600000,0x3f800,0x100,0x200,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x20,0x0,0x0,0x0,0x0,0x1f,0x1f,0x0,0x0,0x0,0x0,0x0,0x80,0x80,0x0,0x0,0x0,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[4];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Polinomios(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Polinomios(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new PolinomiosTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Polinomios(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new PolinomiosTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new PolinomiosTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Polinomios(PolinomiosTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(PolinomiosTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[43];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 19; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 43; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 4; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
