/* Generated By:JavaCC: Do not edit this line. PolinomiosConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PolinomiosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 5;
  /** RegularExpression Id. */
  int INICIO = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELIF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int STOP = 12;
  /** RegularExpression Id. */
  int REDUCIR = 13;
  /** RegularExpression Id. */
  int EVALUAR = 14;
  /** RegularExpression Id. */
  int EXPANDIR = 15;
  /** RegularExpression Id. */
  int FACTORIZAR = 16;
  /** RegularExpression Id. */
  int ORDENAR = 17;
  /** RegularExpression Id. */
  int LEER = 18;
  /** RegularExpression Id. */
  int IMPRIMIR = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int TIPO = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int NUM = 24;
  /** RegularExpression Id. */
  int MAS = 25;
  /** RegularExpression Id. */
  int MENOS = 26;
  /** RegularExpression Id. */
  int MUL = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int POT = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int MAYORIG = 33;
  /** RegularExpression Id. */
  int MENORIG = 34;
  /** RegularExpression Id. */
  int IGUAL = 35;
  /** RegularExpression Id. */
  int DIF = 36;
  /** RegularExpression Id. */
  int MAYOR = 37;
  /** RegularExpression Id. */
  int MENOR = 38;
  /** RegularExpression Id. */
  int ASIG = 39;
  /** RegularExpression Id. */
  int PYC = 40;
  /** RegularExpression Id. */
  int PAR_A = 41;
  /** RegularExpression Id. */
  int PAR_C = 42;
  /** RegularExpression Id. */
  int LLAVE_A = 43;
  /** RegularExpression Id. */
  int LLAVE_C = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"programa\"",
    "\"inicio\"",
    "\"if\"",
    "\"elif\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"stop\"",
    "\"reducir\"",
    "\"evaluar\"",
    "\"expandir\"",
    "\"factorizar\"",
    "\"ordenar\"",
    "\">>\"",
    "\"<<\"",
    "\"true\"",
    "\"false\"",
    "<TIPO>",
    "<ID>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
