/* Generated By:JavaCC: Do not edit this line. clase_6Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clase_6Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOR = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int COMA = 8;
  /** RegularExpression Id. */
  int MAS = 9;
  /** RegularExpression Id. */
  int NUMERO = 10;
  /** RegularExpression Id. */
  int ID = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"for\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "<NUMERO>",
    "<ID>",
  };

}
